var searchData=
[
  ['x',['x',['http://doc.qt.io/qt-5/qpoint.html#x',1,'QPoint::x()'],['http://doc.qt.io/qt-5/qpointf.html#x',1,'QPointF::x()'],['http://doc.qt.io/qt-5/qrect.html#x',1,'QRect::x()'],['http://doc.qt.io/qt-5/qrectf.html#x',1,'QRectF::x()'],['http://doc.qt.io/qt-5/qtabletevent.html#x',1,'QTabletEvent::x()'],['http://doc.qt.io/qt-5/qwheelevent.html#x',1,'QWheelEvent::x()'],['http://doc.qt.io/qt-5/qcontextmenuevent.html#x',1,'QContextMenuEvent::x()'],['http://doc.qt.io/qt-5/qvector2d.html#x',1,'QVector2D::x()'],['http://doc.qt.io/qt-5/qwindow.html#x-prop',1,'QWindow::x()'],['http://doc.qt.io/qt-5/qvector3d.html#x',1,'QVector3D::x()'],['http://doc.qt.io/qt-5/qvector4d.html#x',1,'QVector4D::x()'],['http://doc.qt.io/qt-5/qquaternion.html#x',1,'QQuaternion::x()'],['http://doc.qt.io/qt-5/qenterevent.html#x',1,'QEnterEvent::x()'],['http://doc.qt.io/qt-5/qhelpevent.html#x',1,'QHelpEvent::x()'],['http://doc.qt.io/qt-5/qmouseevent.html#x',1,'QMouseEvent::x()'],['http://doc.qt.io/qt-5/qtextline.html#x',1,'QTextLine::x()'],['http://doc.qt.io/qt-5/qwidget.html#x-prop',1,'QWidget::x()'],['http://doc.qt.io/qt-5/qgraphicsitem.html#x',1,'QGraphicsItem::x()'],['../classOpenOrienteering_1_1MapCoord.html#ab3860cae8ce4e614a1d774b4c0510566',1,'OpenOrienteering::MapCoord::x()']]],
  ['x1',['x1',['http://doc.qt.io/qt-5/qline.html#x1',1,'QLine::x1()'],['http://doc.qt.io/qt-5/qlinef.html#x1',1,'QLineF::x1()']]],
  ['x2',['x2',['http://doc.qt.io/qt-5/qline.html#x2',1,'QLine::x2()'],['http://doc.qt.io/qt-5/qlinef.html#x2',1,'QLineF::x2()']]],
  ['xchanged',['xChanged',['http://doc.qt.io/qt-5/qwindow.html#x-prop',1,'QWindow::xChanged()'],['http://doc.qt.io/qt-5/qgraphicsobject.html#xChanged',1,'QGraphicsObject::xChanged()']]],
  ['xheight',['xHeight',['http://doc.qt.io/qt-5/qfontmetrics.html#xHeight',1,'QFontMetrics::xHeight()'],['http://doc.qt.io/qt-5/qfontmetricsf.html#xHeight',1,'QFontMetricsF::xHeight()'],['http://doc.qt.io/qt-5/qrawfont.html#xHeight',1,'QRawFont::xHeight()']]],
  ['xmlelementreader',['XmlElementReader',['../classOpenOrienteering_1_1XmlElementReader.html#a9207744fdcb8d6a8dcf76746abb7d980',1,'OpenOrienteering::XmlElementReader::XmlElementReader(QXmlStreamReader &amp;xml)'],['../classOpenOrienteering_1_1XmlElementReader.html#ada7747c3c2cf186f572b26579c39ea79',1,'OpenOrienteering::XmlElementReader::XmlElementReader(const XmlElementReader &amp;)=delete'],['../classOpenOrienteering_1_1XmlElementReader.html#a69b6bcd747c1ea05f723b77b569feb46',1,'OpenOrienteering::XmlElementReader::XmlElementReader(XmlElementReader &amp;&amp;)=delete']]],
  ['xmlelementwriter',['XmlElementWriter',['../classOpenOrienteering_1_1XmlElementWriter.html#a7e9b47a4639adfaaa1094cc5d71a40c2',1,'OpenOrienteering::XmlElementWriter::XmlElementWriter(QXmlStreamWriter &amp;xml, const QLatin1String &amp;element_name)'],['../classOpenOrienteering_1_1XmlElementWriter.html#a672fdaa580db9e262324c699239c6a8e',1,'OpenOrienteering::XmlElementWriter::XmlElementWriter(const XmlElementWriter &amp;)=delete'],['../classOpenOrienteering_1_1XmlElementWriter.html#ae4d21db028e0b855d143e6a92209794b',1,'OpenOrienteering::XmlElementWriter::XmlElementWriter(XmlElementWriter &amp;&amp;)=delete']]],
  ['xmlfileexporter',['XMLFileExporter',['../classOpenOrienteering_1_1XMLFileExporter.html#afa71923f216018ee193e2e4039d37543',1,'OpenOrienteering::XMLFileExporter']]],
  ['xmlfileformat',['XMLFileFormat',['../classOpenOrienteering_1_1XMLFileFormat.html#aed34f7ae352dbf6c11d89a759e5dcf59',1,'OpenOrienteering::XMLFileFormat']]],
  ['xmlfileimporter',['XMLFileImporter',['../classOpenOrienteering_1_1XMLFileImporter.html#a3ecf151ecf2d48a9cd2bff599e1a5578',1,'OpenOrienteering::XMLFileImporter']]],
  ['xmlfileimportercolorbacklogitem',['XMLFileImporterColorBacklogItem',['../structOpenOrienteering_1_1XMLFileImporterColorBacklogItem.html#a989f90c6a4e40897dde6c8d195b4750f',1,'OpenOrienteering::XMLFileImporterColorBacklogItem']]],
  ['xmlrecoveryhelper',['XmlRecoveryHelper',['../classOpenOrienteering_1_1XmlRecoveryHelper.html#a1630f3750ba76eab39aed86ee27d3f9e',1,'OpenOrienteering::XmlRecoveryHelper']]],
  ['xoffset',['xOffset',['http://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#xOffset-prop',1,'QGraphicsDropShadowEffect']]],
  ['xored',['xored',['http://doc.qt.io/qt-5/qregion.html#xored',1,'QRegion']]],
  ['xscale',['xScale',['http://doc.qt.io/qt-5/qgraphicsscale.html#xScale-prop',1,'QGraphicsScale']]],
  ['xscalechanged',['xScaleChanged',['http://doc.qt.io/qt-5/qgraphicsscale.html#xScaleChanged',1,'QGraphicsScale']]],
  ['xtilt',['xTilt',['http://doc.qt.io/qt-5/qtabletevent.html#xTilt',1,'QTabletEvent']]],
  ['xtocursor',['xToCursor',['http://doc.qt.io/qt-5/qtextline.html#xToCursor',1,'QTextLine']]],
  ['xtranslationat',['xTranslationAt',['http://doc.qt.io/qt-5/qgraphicsitemanimation.html#xTranslationAt',1,'QGraphicsItemAnimation']]]
];
